sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - npm run semantic-release
env:
  global:
    - secure: buS8H2yGatraVGJxZPfI8ER/dLbEAZDiccIz0OkJ7f0WbxUV1CPMcNF8bXLBAE5lVwC/oke20PlJOYniXduyDJPT7peD6DXamLI/0wMSJA5NdS6wM5ugrCLRIAN+mPi3XG/Qj/LVLhZ6JZHvvahfjlGxg1aLNcfwSeexQhRRm/h+hYN0tWbNihepQxAE59uhllMXKkGFPR+2EIf3BANNZ+0rn5qG0K0pgKanfy2X5Zmdm0FB3/8hGavdKlvdxQpwTUXl3rD+ZWnVDiAGfzW+8gnEHnyatwzqJwQnATeOi0XPZ1rIhp7yMuJAUznN6FXTtMnUjH3xVMWvIFC5iVFzdDOs8+1su5jRNvCKeovliQ3ZWnfBBQ7yJBempl7TY2pQJAl2crHLEnZvZL/SyplsMGdAD2otdixtegvpp+S4CjUJhUOlH4j3ccAtI5KPd8RqWCB7R4zPT6bzVd0SajYu76RSk7oOF091+KoeqPkUFweqVXLXVFAYsLnG1PVf3a76KqHcPqF7nbI6BabCU7nb07mqai2pIRMdy1KgfRW+Mmr/Lg0UAJ3TXJ7kp82B/8i8AJnLqBOdMwE7wKggTsQoFYL3wpvF2iJKkT+i66YW2fLL6q4fidJ5c6zsOJ3kmKbjWNjJiCM9Lf3BG8lJWY6Eo5Cs9miAEcomFJJm+bbXDcg=
    - secure: b1AysHSn7Nvbnt5e4ILsNvjiwF8sDQ19c03AeUgpFjfBsfZ72bBROUn6zb2RAYNcwgVSdavhoLy1Gvnd90RWf2C+rNlJwAnEqEtKIGUMJPMLPCyJLdxhixD7ix2wSSgGVVx8Pzlqt9gWT9dAH+YUlug/fJz1hMGV8MLUI4ZHyihG7PurKSn0CdftVWcHhWjnsjZo2+yFW1tQPq2vCF9DUeUokGdmWrfPHjntxdpcAWZv93OWtaGAXhkKqMob3JJnEmh6ylVr4KergQe9v3YHoUVX01TFm2pzdAWFNrBZfk6SaaioeSapuyMTsefPVMHE00b6qWXFyXc64tZcnouoY+7C5TyliTdtXzdViyhRzM8O+0ChEAwiAr4NgnqIQcJ/qljGo3GjbP2HisymBdWeTAKdH+btHwZwXzRtiQKWS6Ggw9TF4BoyqtbQ/c5BNeRWWkIbO46q9z9tF48Ui8ND6msw+CMMd2LLnWrdxkhKNzFyROaKj/CjV75X0mBCVdq9tDzALYdW6Qlpqh2OguOkPbfKa/fb0SMiZbPo2OuwP8WJEZ2fvM3rQaiqtixW8+zjlDDxh17ee6mce4V6/fKHcIveGHiStfiY6m/6TeLSOuOi6dv11g0Q+EGSTiedR+Q5BlBy9MA8PWLKV6QTNFhT8bhEZIdy7BrXXsTCd2DmlDw=
